version: '3'

services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      FLAG: a

  loginpage:
    build:
      context: ./LoginPage-01
      dockerfile: Dockerfile
    ports: 
      - 3001:3000
    depends_on:
      - "db"

  sql-injection:
    build: 
      context: ./SQL-injection-website-01
      dockerfile: Dockerfile
    ports: 
      - 3002:3000
    depends_on:
      - "db"
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      FLAG: a

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - "loginpage"
      - "sql-injection"