version: '3'

services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: mysql,
      MYSQL_DATABASE: db,
      MYSQL_USER: user,
      MYSQL_PASSWORD: password,

  loginpage:
    build:
      context: ./LoginPage-01
      dockerfile: Dockerfile
    ports: 
      - 3001:3000
    depends_on:
      - "db"

  sql-injection:
    build: 
      context: ./SQL-injection-website-01
      dockerfile: Dockerfile
    ports: 
      - 3002:3000
    depends_on:
      - "db"
    environment:
      DB_DATABASE: db
      DB_HOST: db
      DB_USER: root
      DB_PASS: mysql
      BD_PORT: 3306

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/crt.pem:/etc/nginx/crt.pem
      - ./nginx/key.pem:/etc/nginx/key.pem
    depends_on:
      - "loginpage"
      - "sql-injection"